### ISSUE TITLE
需要点击才可以注入吗？

### ISSUE THREAD

**Issue by wenmin92** [eGust/injector-pro#1]
可不可以提供一个选项，某些组自动注入？

**Comment by eGust** [comment]
啥意思，不管什么网站都在加载完毕之后自动执行注入吗？

**Comment by wenmin92** [comment]
是的，这个选项开启后，新打开的网站都会自动注入设置的脚本和样式。

**Comment by eGust** [comment]
大概看了一下，技术上似乎没什么问题，但是你意识到这样做在安全上潜在着很大的风险吗？

1. 注入的 js 库有可能会覆盖原有的库，导致网站功能异常
1. 来自 cdn 的文件可能有恶意代码，有机会窃取表单中的敏感信息

**Comment by wenmin92** [comment]
确实是不太好。
我本来是想实现这样一个功能——点击快捷键，以某种格式自动复制出当前页面的标题和url，然后toast提示一下复制成功，之后我会将这个复制的链接用在笔记上。
因为浏览器自带的alert()还需要点击一下才可以消失，所以想要第三方的toast库，于是就需要注入了。其实，如果自己熟悉js的话，应该是可以直接代码实现的，可惜太不熟练了。
